frontend:
  image:
    repository: tuanasanh/my-app-frontend-image
    tag: "v1.0.0"
  replicaCount: 2
  service:
    type: NodePort
    port: 3000

backend:
  image:
    repository: tuanasanh/my-app-backend-image
    tag: "v1.0.0"
  replicaCount: 2
  service:
    type: NodePort
    port: 5000
