frontend:
  image:
    repository: tuanasanh/my-app-frontend-image
    tag: "1.0.4"
  replicaCount: 2
  service:
    type: NodePort
    port: 3000

backend:
  image:
    repository: tuanasanh/my-app-backend-image
    tag: "1.0.5"
  replicaCount: 2
  service:
    type: NodePort
    port: 5000
